"""add lead email delivery tracking

Revision ID: c2b380655b4f
Revises: 1eee7e1953a1
Create Date: 2026-08-23 23:04:51.761490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b380655b4f'
down_revision: Union[str, Sequence[str], None] = '1eee7e1953a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'lead_capture',
    sa.Column(
        'delivery_status',
        sa.String(length=30),
        nullable=False,
        server_default='pending',
    )
)
    op.add_column('lead_capture', sa.Column('delivery_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lead_capture', sa.Column('provider_message_id', sa.String(length=255), nullable=True))
    op.add_column('lead_capture', sa.Column('delivery_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_capture', 'delivery_error')
    op.drop_column('lead_capture', 'provider_message_id')
    op.drop_column('lead_capture', 'delivery_timestamp')
    op.drop_column('lead_capture', 'delivery_status')
    # ### end Alembic commands ###
